### ISSUE TITLE
loading jquery issue in atom-shell

### ISSUE THREAD

**Issue by soomtong** [GoBijan/maverix#1]
to try `atom-shell` use this modification

in `index.html`

``` html
<script src="bower_components/jquery/dist/jquery.min.js"/></script>
```

replace this

``` html
<script type="text/javascript">window.$ = window.jQuery = require('./bower_components/jquery/dist/jquery.min.js');</script>
```

refer : https://github.com/atom/atom-shell/issues/254

thanks @tschundeee for this cool

**Comment by joshmarinacci** [comment]
Can we add something to the docs about the right way to load javascript? Most people will simply drop some web content in and expect it to work. It sounds like loading JS via script tags won't work at all. instead you have to use require. I didn't see that documented anywhere.

**Comment by soomtong** [comment]
i think so @joshmarinacci but i can't find any document for these issue. i am a newbie, we need more time :)
and maybe, Github atom team knows this to do, plans to make more reference and examples.

**Comment by gobijan** [comment]
Not maverix related.
