### ISSUE TITLE
Request Title bar buttons

### ISSUE THREAD

**Issue by peterpaulis** [GoBijan/maverix#2]
Title bar buttons for : (close, min, max), fullscreen

**Comment by gobijan** [comment]
Maverix is meant to be used for wrappers like macgap, node-webkit or atom-shell.
Those wrappers bring their own native window control buttons.

What would be your use case?

**Comment by peterpaulis** [comment]
ok, but you can have a wrapper, with a custom title bar (the wrapper doesn't need to expose the native title bar)

**Comment by peterpaulis** [comment]
as the wrapper can be just a plain, plain square container, without anything, just the webview component

**Comment by gobijan** [comment]
wontchange for now.
