### ISSUE TITLE
Nav background color on mouseout

### ISSUE THREAD

**Issue by jasonhinkle** [GoBijan/maverix#4]
On chrome, when you select and then mouseout of a nav item, the background color doesn't remain the correct blue gradient.

![screen shot 2015-05-28 at 2 56 08 pm](https://cloud.githubusercontent.com/assets/313176/7869661/d4cde088-0549-11e5-8e72-becbd53b4316.png)

**Comment by gobijan** [comment]
Aaaaaaaaand FIXED ;)

**Comment by jasonhinkle** [comment]
Awesome - that did the trick.  I just happened to notice that the disabled items (in the demo under "PLACEHOLDER SERVICES") have the same issue.  Perhaps those are just there as a demo and not supposed to be clickable?

**Comment by gobijan** [comment]
Thats on purpose.
